### PR TITLE
Add owner data to interfaces

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/116/
Test PASSed.

**Comment by anthonydillon** [comment]
## QA:

``` bash
python
from theblues.charmstore import CharmStore
cs = CharmStore('http://api.jujugui.org/charmstore/v5')
cs.fetch_interfaces("mysql", "provides")[2][0].get('Meta').get('owner')
```

Check the output contains `User` data

**Comment by kadams54** [comment]
Looks good, both on code :+1: and QA :ok: - thanks!

**Comment by fabricematrat** [comment]
:+1:

**Comment by makyo** [comment]
👍

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
