### PR TITLE
Enable py34 by removing hard libmacaroons dependency.

### PR DESCRIPTION
**Pull request by jcsackett**

### CODE REVIEW

**Comment by jcsackett** [comment]
QA:

There  is no QA; you can try out importing/using it on py27 and py34 if you like, but the actual lib itself is still a little uneven outside of charmstore.py

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/86/
Test PASSed.

**Comment by marcoceppi** [comment]
:+1:

**Comment by bac** [comment]
:+1:

**Comment by jcsackett** [comment]
Thanks for the reviews!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
