### PR TITLE
Handle 407 as EntityNotFound for charmstore.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by fabricematrat** [comment]
The goal is to be able to treat 407 from charmstore as equivalent as an EntityNotFound.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/10/
Test PASSed.

**Comment by frankban** [comment]
:+1: 
Out of curiosity: in which cases a 407 is returned by the charm store?
Should we add a comment about that?

**Comment by jcsackett** [comment]
:+1: @fabricematrat thanks!

No qa, but I don't think this really requires any.

**Comment by fabricematrat** [comment]
:shipit:  thanks @jaycee && @frankban

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
