### PR TITLE
idm: add missing macaroon params

### PR DESCRIPTION
**Pull request by frankban**
This is just a change requested at https://github.com/juju/theblues/pull/59 but not committed.

### CODE REVIEW

**Comment by frankban** [comment]
Self-review: trivial.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/theblues-lib-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/theblues-lib/208/

**Comment by frankban** [comment]
:shipit:

**Pull request merged**
