### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by adam-stokes**
This import currently fails because of an `ImportError: No module named 'errors'` so we make the import relative.

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by kadams54** [comment]
:+1: from me on the code change. I'm going to give this a whirl and verify that it doesn't break anything.

**Comment by kadams54** [comment]
I'm going to give this a whirl and verify that it doesn't break anything.

**Comment by adam-stokes** [comment]
Thanks, I wasn't sure how it was working before since doing a straight pip install theblues showed the traceback

**Comment by kadams54** [comment]
QA is :ok:. :shipit:

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/theblues-lib-merge/15

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
