### PR TITLE
Update RELEASE_PROCESS.rst

### PR DESCRIPTION
**Pull request by bac**
Fix ~/.pypirc instructions

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/78/
Test PASSed.

**Comment by mitechie** [comment]
:+1: no qa

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
