### PR TITLE
Add resources in meta search and resource_url method.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/93/
Test PASSed.

**Comment by fabricematrat** [comment]
QA:

python
from theblues.charmstore import CharmStore
cs = CharmStore('http://api.jujugui.org/charmstore/v5')
cs.entity("~yellow/starsay-test-0")

Check that we have some resources as output.
then check the resource_url is correct
cs.resource_url("~yellow/starsay-test-0", "for-install", 0)

**Comment by jcsackett** [comment]
:+1:

**Comment by jcsackett** [comment]
QA notes:

Followed the returned url for the resource and got "hello" which seems like a resource file.

**Comment by jcsackett** [comment]
QA OK.

**Comment by jrwren** [comment]
👍

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
