### PR TITLE
Update Makefile to work on clean trusty machine.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/146/
Test PASSed.

**Comment by bac** [comment]
On a new trusty machine, `make check` does not work out-of-the-box due to missing system dependencies.

To see this, in a new trusty lxd grab the current master and run:

```
make check
```

💣 

With this branch run:

```
make sysdeps check
```

🍗

**Comment by kadams54** [comment]
QA is :ok: on a clean trusty VM and code looks :+1: to me. Thanks @bac!

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
