### PR TITLE
Make it possible to disable stats collection

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
CanonicalLtd/jujucharms.com#551

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by jcsackett** [comment]
Tests running: http://ci.jujugui.org:8080/job/theblues-lib/206/console

**Comment by jcsackett** [comment]
Looks good, @ChrisMacNaughton -- thanks!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/theblues-lib-merge

**Review by jcsackett — APPROVED** [review]

**Pull request merged**
