### PR TITLE
Support searching on type.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/26/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/27/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/28/
Test PASSed.

**Comment by fabricematrat** [comment]
QA Notes:

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from theblues.charmstore import CharmStore
>>> cs = CharmStore('https://api.jujucharms.com/v4')                                                                                                                                                            
>>> cs.search('mysql', doc_type='bundle')                                                                                                                                                                
[{u'Id': u'cs:~lazypower/bundle/hdp-hadoop-hive-mysql-4'}, {u'Id': u'cs:~asanjar/bundle/hdp-hadoop-hive-mysql-2'}, {u'Id': u'cs:bundle/data-analytics-with-sql-like-6'}, {u'Id': u'cs:~bigdata-dev/bundle/apache-analytics-sql-3'}, {u'Id': u'cs:~bigdata-charmers/bundle/data-analytics-with-sql-like-6'}]
>>> cs.search('mysql', doc_type='charm')
[{u'Id': u'cs:trusty/mysql-25'}, {u'Id': u'cs:precise/mysql-51'}, {u'Id': u'cs:~justin-fathomdb/trusty/mysql-1'}, {u'Id': u'cs:~cf-charmers/trusty/cf-mysql-broker-23'}, {u'Id': u'cs:~tribaal/trusty/mysql-1'}, {u'Id': u'cs:~brian-albrecht/trusty/mysql-1'}, {u'Id': u'cs:~a.rosales/trusty/mysql-0'}, {u'Id': u'cs:~bjornt/trusty/mysql-0'}, {u'Id': u'cs:~cf-charmers/trusty/mysql-0'}, {u'Id': u'cs:~prismakov/trusty/cf-mysql-broker-1'}]
>>> cs.search('mysql', doc_type='wrong')
[{u'Id': u'cs:trusty/mysql-25'}, {u'Id': u'cs:precise/mysql-51'}, {u'Id': u'cs:~justin-fathomdb/trusty/mysql-1'}, {u'Id': u'cs:~cf-charmers/trusty/cf-mysql-broker-23'}, {u'Id': u'cs:~tribaal/trusty/mysql-1'}, {u'Id': u'cs:~brian-albrecht/trusty/mysql-1'}, {u'Id': u'cs:~a.rosales/trusty/mysql-0'}, {u'Id': u'cs:~bjornt/trusty/mysql-0'}, {u'Id': u'cs:~cf-charmers/trusty/mysql-0'}, {u'Id': u'cs:~prismakov/trusty/cf-mysql-broker-1'}]

```

Just wonder if we should validate the doc_type as CS is defaulting to charm for invalid doc_type.

:+1:  With one question

**Comment by jcsackett** [comment]
:+1: thanks @kadams54

**Comment by kadams54** [comment]
@fabricematrat Good question. We don't validate on any of the other parameters passed in (or at least not here) so I didn't on `doc_type`.

**Comment by kadams54** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
