### PR TITLE
Add charm-actions data to charm_data

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/theblues-lib/186/

**Comment by anthonydillon** [comment]
## QA:

``` bash
python
from theblues.charmstore import CharmStore
cs = CharmStore('http://api.jujugui.org/charmstore/v5')
entity = cs.entity('ceph')
entity.get('Meta').get('charm-actions')
```

Check the output contains `ActionSpecs` data

**Review by frankban — APPROVED** [review]
So I guess we don't have a test for the resulting call.
But it's not the scope for this branch.

**Comment by anthonydillon** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
