### PR TITLE
Expose common-info.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/theblues-lib/42/
Test PASSed.

**Comment by fabricematrat** [comment]
QA:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from theblues.charmstore import CharmStore
> > > cs = CharmStore('http://api.jujugui.org/charmstore/v4')
> > > cs.entity('~fabricematrat/trusty/beaver-0', False)                                                                                                                                                          

The results should contains common-info and homepage inside.

**Comment by frankban** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by fabricematrat** [comment]
:shipit: thanks @mhilton && @frankban

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/theblues-lib-merge

**Pull request merged**
